# Build settings
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components, src, tcc/*.docx ]
timezone: America/Sao_Paulo
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
sass:
    sass_dir: _sass
    style: :compressed

# Site settings
destination: ../gh-pages
permalink: pretty
title: CPS Front-end
description: Manual e framework front-end para projetos web do Centro Paula Souza.
baseurl: "/cps-frontend/"
baseurl_content: "http://adammacias.github.io/cps-frontend/assets/"
url: "http://adammacias.github.io"

# Custom vars
current_version:  1.0.0-alpha
repo:             https://github.com/adammacias/cps-frontend

download:
  source:         https://github.com/adammacias/cps-frontend/releases/download/v1.0.0-alpha/cps-v1.0.0-alpha.zip
  dist:           https://github.com/adammacias/cps-frontend/releases/download/v1.0.0-alpha/cps-v1.0.0-alpha-dist.zip
  brand:
    manual:       http://www.centropaulasouza.sp.gov.br/quem-somos/manual-de-identidade-logo-novo/manual/manual-centro-paula-souza-2015-set.pdf
    assets:       https://github.com/adammacias/cps-frontend/releases/download/v1.0.0-alpha/cps-v1.0.0-alpha-brand.zip

cdn:
  css:            http://bb.adammacias.com.br/cps-frontend/assets/css/centropaulasouza.css
  js:             http://bb.adammacias.com.br/cps-frontend/assets/js/main.min.js
  jquery:         https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

