# Build settings
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components, src ]
timezone: America/Sao_Paulo # e.g. America/New_York or America/Sao_Paulo
markdown: kramdown # rdiscount
highlighter: pygments
sass:
    sass_dir: _sass
    style: :expanded # :nested ? :compact ? :expanded :compressed | Different Sass Output Styles: http://bit.ly/1K5wPnC

# Site settings
permalink: /posts/:title
title: Centro Paula Souza Styleguide
description: Guia de estilos de Fatecs e Etecs para desenvolvedores e designers.
baseurl: "/" # the subpath of your site, e.g. /blog/
baseurl_content: "http://localhost:4000/content/" # put path absolute
url: "http://localhost:4000" # the base hostname & protocol for your site

# Custom variables
analytics: UA-0000000-0
version: 1.0
author:
  name: Adam Macias
  url: http://adammacias.com
  github: adammacias
  twitter: adammacias
  facebook: adam.requena.macias
  instagram: adammacias
  gplus: 117839494541292456644
  email: eu@adammacias.com

repo_url: https://github.com/adammacias/cps-bootstrap

############################################################################

# Mode Developing for files not minify, livereload and etc.
mode: dev
# Devs Tutorial
# jekyll serve --config _config-dev.yml --w --drafts
# url 4 page:       {{ "index.html" | prepend: site.baseurl | prepend: site.url }} - or - {{ site.baseurl | prepend: site.url | append: "index.html" }}
# url 4 css:        {{ "css/main.css" | prepend: site.baseurl | prepend: site.url }}
# url 4 content:    {{ "favicon.png" | prepend: site.baseurl_content }}
