# Build settings
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components, src, tcc/*.docx ]
timezone: America/Sao_Paulo # e.g. America/New_York or America/Sao_Paulo
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
sass:
    sass_dir: _sass
    style: :expanded # :nested ? :compact ? :expanded :compressed | Different Sass Output Styles: http://bit.ly/1K5wPnC

# Site settings
permalink: pretty
title: CPS Front-end
description: Guia de estilos do Centro Paula Souza para desenvolvedores web.
baseurl: "/" # the subpath of your site, e.g. /blog/
baseurl_content: "http://localhost:4000/assets/" # put path absolute
url: "http://localhost:4000" # the base hostname & protocol for your site

# Custom vars
current_version:  1.0.0-alpha
repo:             https://github.com/adammacias/cps-bootstrap

download:
  source:         https://github.com/adammacias/cps-bootstrap/releases/download/v1.0.0-alpha/cps-v1.0.0-alpha.zip
  dist:           https://github.com/adammacias/cps-bootstrap/releases/download/v1.0.0-alpha/cps-v1.0.0-alpha-dist.zip
  brand:
    manual:       http://www.centropaulasouza.sp.gov.br/quem-somos/manual-de-identidade-logo-novo/manual/manual-centro-paula-souza-2015-set.pdf
    assets:       https://github.com/adammacias/cps-bootstrap/releases/download/v1.0.0-alpha/cps-v1.0.0-alpha-brand.zip

cdn:
  css:            https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css
  js:             https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js
  jquery:         https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js

############################################################################

# Mode Developing for files not minify, livereload and etc.
mode: dev
# Devs Tutorial
# jekyll serve --config _config-dev.yml --w --drafts
# jekyll s --config _config-dev.yml
# url 4 page:       {{ "index.html" | prepend: site.baseurl | prepend: site.url }} - or - {{ site.baseurl | prepend: site.url | append: "index.html" }}
# url 4 css:        {{ "css/main.css" | prepend: site.baseurl | prepend: site.url }}
# url 4 content:    {{ "favicon.png" | prepend: site.baseurl_content }}
# Dependencies

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

